name: iOS Build and TestFlight Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
      APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
      APP_STORE_API_KEY_CONTENT: ${{ secrets.APP_STORE_API_KEY_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies via Bundler
        working-directory: ios
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Add bundler path to system PATH
        run: echo "$(pwd)/ios/vendor/bundle/ruby/3.1.0/bin" >> $GITHUB_PATH

      - name: Run Fastlane beta lane
        working-directory: ios
        run: bundle exec fastlane beta
