name: iOS Build and TestFlight Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
      APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
      APP_STORE_API_KEY_CONTENT: ${{ secrets.APP_STORE_API_KEY_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install --legacy-peer-deps

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install iOS dependencies
        working-directory: ios
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: |
          gem install cocoapods
          pod install --repo-update

      - name: Run Fastlane beta lane
        working-directory: ios
        run: bundle exec fastlane beta
