name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    name: Validate PR (Type Check, Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --force

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run Tests (Jest)
        run: npm test
