name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: PR Test Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (legacy peer deps)
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test
